CREATE OR REPLACE PROCEDURE GEN_NEXT_SEQUENCE_PK(I_NAME IN VARCHAR2 , O_VALUE OUT NUMBER) IS
BEGIN
  UPDATE NSC_MEAP_SEQUENCE SET "CURRENT" = "CURRENT" + "STEP"  WHERE ID = I_NAME;
  IF SQL%NOTFOUND THEN
    INSERT INTO NSC_MEAP_SEQUENCE("ID","CURRENT","STEP") VALUES(I_NAME,100,1);
  END IF;
  SELECT "CURRENT" INTO O_VALUE FROM NSC_MEAP_SEQUENCE WHERE ID = I_NAME;  
END GEN_NEXT_SEQUENCE_PK;