CREATE TABLE NSC_MEAP_SEQUENCE (
	"ID" VARCHAR2(128) NOT NULL PRIMARY KEY,--主键
	"CURRENT" NUMBER(16) DEFAULT 0 NOT NULL,--当前值
	"STEP" NUMBER(4) DEFAULT 1 NOT NULL--每步值
);

CREATE TABLE NSC_MEAP_SCHEDULE (
	"ID" VARCHAR2(32) NOT NULL PRIMARY KEY,
	"SECOND" NUMBER(11) DEFAULT -1 NOT NULL,--秒,
	"MINUTE" NUMBER(11) DEFAULT -1 NOT NULL,--分钟,
	"HOUR" NUMBER(11)  DEFAULT -1 NOT NULL,--小时,
	"WEEKDAY" NUMBER(11) DEFAULT -1 NOT NULL,--星期几,
	"DAYOFMONTH" NUMBER(11)  DEFAULT -1 NOT NULL,--几号,
	"MONTH" NUMBER(2)  DEFAULT -1 NOT NULL,--那个月,
	"TASK" VARCHAR2(128) DEFAULT '' NOT NULL--目标类
);

CREATE TABLE NSC_MEAP_APP_TOKEN (
  "ID" VARCHAR2(64) NOT NULL PRIMARY KEY,
  "USERTOKEN" VARCHAR2(64) DEFAULT 'ANONYMOUS' NOT NULL,--用户令牌,
  "ARTIFACTID" VARCHAR2(64) DEFAULT 'GLOBLE' NOT NULL,
  "DEVICE" VARCHAR2(16) NOT NULL,--设备,
  "DEVICEID" VARCHAR2(64) NOT NULL,--设备ID,
  "SALT" VARCHAR2(128) NOT NULL,--盐,
  "SALTKEY" VARCHAR2(64) NOT NULL,--加密盐的秘钥,
  "PUBLICKEY" VARCHAR2(1024) NOT NULL,--公钥,
  "PUSHTOKEN" VARCHAR2(128) NOT NULL,--推送令牌,
  "CREATEDTIME" NUMBER(16) DEFAULT 0 NOT NULL,--创建时间,
  "VERIFY" NUMBER(1) NOT NULL--是否已经通过验证
);
CREATE INDEX IDX_NMAT_VERIFY ON NSC_MEAP_APP_TOKEN("VERIFY");
CREATE INDEX IDX_NMAT_USERTOKEN ON NSC_MEAP_APP_TOKEN("USERTOKEN");
CREATE UNIQUE INDEX IDX_NMAT_DDP ON NSC_MEAP_APP_TOKEN("ARTIFACTID","DEVICE","DEVICEID");

CREATE TABLE NSC_MEAP_USER_TOKEN (
	"ID" VARCHAR2(64) NOT NULL PRIMARY KEY,--用户令牌,
	"USERID" VARCHAR2(128) NOT NULL UNIQUE--用户唯一性ID比如EMAIL、用户名、USERID等
);

CREATE TABLE NSC_MEAP_FILE_TOKEN (
	"ID" VARCHAR2(32) NOT NULL PRIMARY KEY,
	"USERTOKEN" VARCHAR2(64),--用户令牌,
	"APPTOKEN" VARCHAR2(64) NOT NULL,--应用令牌,
	"FILENAME" VARCHAR2(64) NOT NULL,--文件名,
	"DIGEST" VARCHAR2(64) NOT NULL,--摘要,
	"ALGORITHM" VARCHAR2(32) NOT NULL,--算法,
	"FILESIZE" NUMBER(16) NOT NULL,--文件大小,
	"FILEPOS" NUMBER(16) NOT NULL,--文件位置,
	"FILETYPE" VARCHAR2(32),--文件类型扩展名,
	"FILESTATUS" VARCHAR2(32),--文件状态,
	"CREATEDTIME" NUMBER(16) NOT NULL--创建时间
);
CREATE INDEX IDX_NMFT_USERTOKEN ON NSC_MEAP_FILE_TOKEN("USERTOKEN");
CREATE INDEX IDX_NMFT_APPTOKEN ON NSC_MEAP_FILE_TOKEN("APPTOKEN");

CREATE TABLE NSC_MEAP_QUEUE_PUSH (
	"ID" VARCHAR2(32) NOT NULL PRIMARY KEY,
	"PRIORITY" NUMBER(1) NOT NULL,--优先级,
	"TYPE" VARCHAR2(32) NOT NULL,--类型,
	"DEVICE" VARCHAR2(64) NOT NULL,--设备,
	"PUSHTOKEN" VARCHAR2(64) NOT NULL,--推送ID,
	"MESSAGEID" VARCHAR2(40) NOT NULL,--消息ID,
	"TITLE" VARCHAR2(64),--标题,
	"MESSAGE" VARCHAR2(256) NOT NULL,--信息内容,
	"CALLBACK" NUMBER(1) NOT NULL,--是否需要回调,
	"CREATEDTIME" NUMBER(16) NOT NULL--创建时间
);
CREATE INDEX IDX_NMQP_PRIORITY ON NSC_MEAP_QUEUE_PUSH("PRIORITY");
CREATE INDEX IDX_NMQP_DEVICE ON NSC_MEAP_QUEUE_PUSH("DEVICE");
CREATE INDEX IDX_NMQP_CREATEDTIME ON NSC_MEAP_QUEUE_PUSH("CREATEDTIME");

CREATE TABLE NSC_MEAP_QUEUE_OUTTER (
	"ID" VARCHAR2(32) NOT NULL PRIMARY KEY,
	"SUBJECT" VARCHAR2(32),--主题,
	"COMMAND" VARCHAR2(512) NOT NULL,--指令,
	"CREATEDTIME" NUMBER(16) NOT NULL,--创建时间,
	"EXPIREDTIME" NUMBER(16) NOT NULL,--过期时间,
	"NEEDPROMPT" NUMBER(1) NOT NULL,--需要提示,
	"PUSHPROMPTTEXT" VARCHAR2(128) NOT NULL,--提示文本,
	"HASPROMPTTIMES" NUMBER(2) DEFAULT 0 NOT NULL,--已经提示次数,
	"PROMPTTIMES" NUMBER(2) DEFAULT 0 NOT NULL,--总提示次数,
	"PROMPTMINUTEPERIOD" NUMBER(4) DEFAULT 0 NOT NULL,--提示分钟周期,
	"NEXTPROMPTTIME" NUMBER(16) NOT NULL,--下一次提示时间,
	"TOKENTYPE" VARCHAR2(16) NOT NULL,--令牌类型,
	"TOKEN" VARCHAR2(64) NOT NULL--令牌
);
CREATE INDEX IDX_NMQO_CREATEDTIME ON NSC_MEAP_QUEUE_OUTTER("CREATEDTIME");
CREATE INDEX IDX_NMQO_EXPIREDTIME ON NSC_MEAP_QUEUE_OUTTER("EXPIREDTIME");
CREATE INDEX IDX_NMQO_NEEDPROMPT ON NSC_MEAP_QUEUE_OUTTER("NEEDPROMPT");
CREATE INDEX IDX_NMQO_NEXTPROMPTTIME ON NSC_MEAP_QUEUE_OUTTER("NEXTPROMPTTIME");
CREATE INDEX IDX_NMQO_TT_T ON NSC_MEAP_QUEUE_OUTTER("TOKENTYPE","TOKEN");

CREATE TABLE NSC_MEAP_SSO_USER (
  "USERNAME" VARCHAR2(64) NOT NULL PRIMARY KEY,
  "PASSWORD" VARCHAR2(32) NOT NULL
);

CREATE TABLE NSC_MEAP_SSO_USER_RECORD (
  "ID"	VARCHAR2(32) NOT NULL PRIMARY KEY,
  "CREATETIME" NUMBER(16) NOT NULL,
  "LASTIP" VARCHAR(32),
  "USERNAME" VARCHAR(64)
);
CREATE INDEX IDX_NMSUR_USERNAME ON NSC_MEAP_SSO_USER_RECORD("USERNAME");

CREATE TABLE NSC_MEAP_SAMPLE_USER (
	"ID" VARCHAR2(64) NOT NULL PRIMARY KEY,
	"USERNAME" VARCHAR2(64) NOT NULL UNIQUE,
	"PASSWORD" VARCHAR2(64) NOT NULL
);

CREATE TABLE NSC_MEAP_SAMPLE_USERFILEMAP (
	"ID" VARCHAR2(64) NOT NULL,
	"MEETDETAILID" VARCHAR2(64) NOT NULL PRIMARY KEY,
	"FILETOKEN" VARCHAR2(64) NOT NULL UNIQUE,
	"USERTOKEN" VARCHAR2(64) NOT NULL
);

CREATE TABLE NSC_MEAP_SAMPLE_MEETDETAIL (
	"ID" VARCHAR2(64) NOT NULL PRIMARY KEY,
	"TITLE" VARCHAR2(64) NOT NULL,
	"RECOMMEND" VARCHAR2(128) NOT NULL,
	"PLACE" VARCHAR2(256) NOT NULL,
	"TIME" NUMBER(16) NOT NULL
);


CREATE TABLE NSC_MEAP_SAMPLE_MEETFILE (
	"ID" VARCHAR2(64) NOT NULL PRIMARY KEY,
	"MEETID" VARCHAR2(64) NOT NULL,
	"FILENAME" VARCHAR2(128) NOT NULL,
	"FILEURL" VARCHAR2(256) NOT NULL
);
CREATE INDEX IDX_NMSMD_MEETID ON NSC_MEAP_SAMPLE_MEETFILE("MEETID");

CREATE TABLE NSC_MEAP_SAMPLE_ROLE (
	"ID" VARCHAR2(64) NOT NULL PRIMARY KEY,
	"NAME" VARCHAR2(64) NOT NULL UNIQUE
);

CREATE TABLE NSC_MEAP_SAMPLE_PERMISSION (
	"ID" VARCHAR2(64) NOT NULL PRIMARY KEY,
	"NAME" VARCHAR2(64) NOT NULL UNIQUE,
	"VALUE" VARCHAR2(64) NOT NULL UNIQUE
);

CREATE TABLE NSC_MEAP_SAMPLE_USERROLEMAP (
	"ID" VARCHAR2(64) NOT NULL PRIMARY KEY,
	"USERTOKEN" VARCHAR2(64) NOT NULL,
	"ROLEID" VARCHAR2(64) NOT NULL,
	CONSTRAINT FK_NMSURM_USERTOKEN FOREIGN KEY("USERTOKEN") REFERENCES NSC_MEAP_USER_TOKEN("ID"),
	CONSTRAINT FK_NMSURM_ROLEID FOREIGN KEY("ROLEID") REFERENCES NSC_MEAP_SAMPLE_ROLE("ID")
);

CREATE TABLE NSC_MEAP_SAMPLE_ROLEPERMMAP (
	"ID" VARCHAR2(64) NOT NULL PRIMARY KEY,
	"ROLEID" VARCHAR2(64) NOT NULL,
	"PERMISSIONID" VARCHAR2(64) NOT NULL,
	CONSTRAINT FK_NMSRPM_RID FOREIGN KEY("ROLEID") REFERENCES NSC_MEAP_SAMPLE_ROLE("ID"),
	CONSTRAINT FK_NMSRPM_PID FOREIGN KEY("PERMISSIONID") REFERENCES NSC_MEAP_SAMPLE_PERMISSION("ID")
);
